<?php

namespace Database\Seeders;

use App\Models\MediaAlbum;
use App\Models\MediaGallery;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MediaGallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        MediaAlbum::insert([
            [
                'id' => 1,
                'title' => 'Demo',
                'content' => 'Demo Album',
                'subcontent' => 'Demo Album',
                'albumtype' => 'photo',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:17:44',
                'updated_at' => '2024-07-27 02:17:46',
            ],
            [
                'id' => 2,
                'title' => 'Demo 2',
                'content' => 'Demo Album 2',
                'subcontent' => 'Demo Album 2',
                'albumtype' => 'photo',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:17:56',
                'updated_at' => '2024-07-27 02:18:04',
            ],
            [
                'id' => 3,
                'title' => 'Demo 3',
                'content' => 'Demo Album 3',
                'subcontent' => 'Demo Album 3',
                'albumtype' => 'photo',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:18:02',
                'updated_at' => '2024-07-27 02:18:06',
            ],
        ]);

        MediaGallery::insert([
            [
                'id' => 1,
                'type' => 'photo',
                'album_id' => 1,
                'name' => null,
                'media' => 'gallery1.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 2,
                'type' => 'photo',
                'album_id' => 2,
                'name' => null,
                'media' => 'gallery2.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 3,
                'type' => 'photo',
                'album_id' => 3,
                'name' => null,
                'media' => 'gallery3.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 4,
                'type' => 'photo',
                'album_id' => 1,
                'name' => null,
                'media' => 'gallery1.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 5,
                'type' => 'photo',
                'album_id' => 2,
                'name' => null,
                'media' => 'gallery2.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 6,
                'type' => 'photo',
                'album_id' => 3,
                'name' => null,
                'media' => 'gallery3.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 7,
                'type' => 'photo',
                'album_id' => 1,
                'name' => null,
                'media' => 'gallery3.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 8,
                'type' => 'photo',
                'album_id' => 2,
                'name' => null,
                'media' => 'gallery2.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 9,
                'type' => 'photo',
                'album_id' => 3,
                'name' => null,
                'media' => 'gallery1.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => null,
                'sub_content' => null,
                'position' => 0,
                'url' => null,
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:19:11',
                'updated_at' => '2024-07-27 02:19:11',
            ],
            [
                'id' => 10,
                'type' => 'video',
                'album_id' => null,
                'name' => 'Laravel 10 React with Vite Full Stack',
                'media' => '16688105-822e-4016-88a1-819071cdb870.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => 'Laravel 10 React with Vite Full Stack\r\nSource code : https://www.tutussfunny.com/react-js-...\r\nDownload the Learn Pro',
                'sub_content' => null,
                'position' => 0,
                'url' => 'https://www.youtube.com/watch?v=Kzs-f4JxvPI&t=2470s',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:21:30',
                'updated_at' => '2024-07-27 02:21:33',
            ],
            [
                'id' => 11,
                'type' => 'video',
                'album_id' => null,
                'name' => 'Laravel 10 React with Vite Full Stack',
                'media' => '16688105-822e-4016-88a1-819071cdb870.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => 'Laravel 10 React with Vite Full Stack\r\nSource code : https://www.tutussfunny.com/react-js-...\r\nDownload the Learn Pro',
                'sub_content' => null,
                'position' => 0,
                'url' => 'https://www.youtube.com/watch?v=Kzs-f4JxvPI&t=2470s',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:21:30',
                'updated_at' => '2024-07-27 02:21:33',
            ],
            [
                'id' => 12,
                'type' => 'video',
                'album_id' => null,
                'name' => 'Laravel 10 React with Vite Full Stack',
                'media' => '16688105-822e-4016-88a1-819071cdb870.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => 'Laravel 10 React with Vite Full Stack\r\nSource code : https://www.tutussfunny.com/react-js-...\r\nDownload the Learn Pro',
                'sub_content' => null,
                'position' => 0,
                'url' => 'https://www.youtube.com/watch?v=Kzs-f4JxvPI&t=2470s',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:21:30',
                'updated_at' => '2024-07-27 02:21:33',
            ],
            [
                'id' => 13,
                'type' => 'video',
                'album_id' => null,
                'name' => 'Laravel 10 React with Vite Full Stack',
                'media' => '16688105-822e-4016-88a1-819071cdb870.png',
                'mob_media' => null,
                'sub_media' => null,
                'content' => 'Laravel 10 React with Vite Full Stack\r\nSource code : https://www.tutussfunny.com/react-js-...\r\nDownload the Learn Pro',
                'sub_content' => null,
                'position' => 0,
                'url' => 'https://www.youtube.com/watch?v=Kzs-f4JxvPI&t=2470s',
                'status' => 1,
                'added_by' => 1,
                'created_at' => '2024-07-27 02:21:30',
                'updated_at' => '2024-07-27 02:21:33',
            ],
        ]);
    }
}
